export default function() {
  return [
    {title: 'Javascript: The Good Parts', pages: 101},
    {title: 'Harry Potter', pages: 39},
    {title: 'The Dark Tower', pages: 85},
    {title: 'Eloquent Ruby', pages: 1}
  ]
}

// our application's state is generated by reducers. the thing returned is the VALUE for one of the keys in our main root reducer.

// any other file can import this file and it will have access to this function
